Nop.Plugin.Misc.Newsman/Controllers/NewsmanController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.ScheduleTasks;
using Nop.Plugin.Misc.Newsman.Models;
using Nop.Plugin.Misc.Newsman.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.ScheduleTasks;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Nop.Services.Catalog;
using Product = Nop.Plugin.Misc.Newsman.Models.Product;
using Cart = Nop.Plugin.Misc.Newsman.Models.Cart;
using Order = Nop.Plugin.Misc.Newsman.Models.Order;
using Nop.Services.Media;
using Nop.Services.Seo;
using Nop.Services.Orders;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Nop.Services.Common;
using Nop.Services.Customers;
using Nop.Core.Domain.Orders;

namespace Nop.Plugin.Misc.Newsman.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class NewsmanController : BasePluginController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IScheduleTaskService _scheduleTaskService;
        private readonly ISettingService _settingService;
        private readonly IStaticCacheManager _staticCacheManager;
        private readonly IStoreContext _storeContext;
        private readonly IStoreService _storeService;
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;
        private readonly IPictureService _pictureService;
        private readonly IUrlRecordService _urlRecordRepository;
        private readonly IAddressService _addressService;
        private readonly ICustomerService _customerService;
        private readonly INewsLetterSubscriptionService _newsLetterSubscriptionService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IWorkContext _workContext;
        private readonly NewsmanManager _newsmanManager;

        #endregion

        #region Ctor

        public NewsmanController(
            ILocalizationService localizationService,
            INotificationService notificationService,
            IScheduleTaskService scheduleTaskService,
            ISettingService settingService,
            IStaticCacheManager cacheManager,
            IStoreContext storeContext,
            IStoreService storeService,
            IProductService productService,
            IOrderService orderService,
            IPictureService pictureService,
            IUrlRecordService urlRecordRepository,
            IAddressService addressService,
            ICustomerService customerService,
            INewsLetterSubscriptionService newsLetterSubscriptionService,
            IShoppingCartService shoppingCartService,
            IWorkContext workContext,
            NewsmanManager newsmanManager)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _scheduleTaskService = scheduleTaskService;
            _settingService = settingService;
            _staticCacheManager = cacheManager;
            _storeContext = storeContext;
            _storeService = storeService;
            _productService = productService;
            _pictureService = pictureService;
            _urlRecordRepository = urlRecordRepository;
            _orderService = orderService;
            _addressService = addressService;
            _customerService = customerService;
            _newsLetterSubscriptionService = newsLetterSubscriptionService;
            _shoppingCartService = shoppingCartService;
            _workContext = workContext;
            _newsmanManager = newsmanManager;
        }

        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public async Task<IActionResult> Configure()
        {
            //load settings for a chosen store scope
            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var newsmanSettings = await _settingService.LoadSettingAsync<NewsmanSettings>(storeId);

            //prepare model
            var model = new ConfigurationModel
            {
                UserId = newsmanSettings.UserId,
                ApiKey = newsmanSettings.ApiKey,
                ImportType = newsmanSettings.ImportType,
                AllowApi = newsmanSettings.AllowApi,
                ListId = newsmanSettings.ListId,
                ListId_OverrideForStore = storeId > 0 && await _settingService.SettingExistsAsync(newsmanSettings, settings => settings.ListId, storeId),
                SegmentId = newsmanSettings.SegmentId,
                SegmentId_OverrideForStore = storeId > 0 && await _settingService.SettingExistsAsync(newsmanSettings, settings => settings.SegmentId, storeId),
                ActiveStoreScopeConfiguration = storeId
            };

            model.ImportType = newsmanSettings.ImportType ?? model.AvailableImportTypes.FirstOrDefault().Value;
            model.AllowApi = string.IsNullOrEmpty(newsmanSettings.AllowApi) ? model.AvailableApi.LastOrDefault().Value : newsmanSettings.AllowApi;

            //prepare available lists
            if (!string.IsNullOrEmpty(newsmanSettings.ApiKey) && !string.IsNullOrEmpty(newsmanSettings.UserId))
                model.AvailableLists = _newsmanManager.GetAvailableListsAsync() ?? new List<SelectListItem>();

            var defaultListId = newsmanSettings.ListId;
            if (!model.AvailableLists.Any())
            {
                model.AvailableLists.Add(new SelectListItem
                {
                    Text = "No lists present",
                    Value = Guid.Empty.ToString()
                });
                defaultListId = Guid.Empty.ToString();
            }
            else if (string.IsNullOrEmpty(newsmanSettings.ListId) || newsmanSettings.ListId.Equals(Guid.Empty.ToString()))
                defaultListId = model.AvailableLists.FirstOrDefault()?.Value;

            //prepare available segments
            if (!string.IsNullOrEmpty(newsmanSettings.ListId) || !newsmanSettings.ListId.Equals(Guid.Empty.ToString()))
                model.AvailableSegments = _newsmanManager.GetAvailableSegmentsAsync() ?? new List<SelectListItem>();

            var defaultSegmentId = newsmanSettings.SegmentId;
            if (!model.AvailableSegments.Any())
            {
                model.AvailableSegments.Add(new SelectListItem
                {
                    Text = "No list selected",
                    Value = Guid.Empty.ToString()
                });
                defaultSegmentId = Guid.Empty.ToString();
            }
            else if (string.IsNullOrEmpty(newsmanSettings.SegmentId) || newsmanSettings.SegmentId.Equals(Guid.Empty.ToString()))
                defaultSegmentId = model.AvailableSegments.FirstOrDefault()?.Value;

            //set the default list & segment
            model.ListId = defaultListId;
            newsmanSettings.ListId = defaultListId;
            await _settingService.SaveSettingOverridablePerStoreAsync(newsmanSettings, settings => settings.ListId, model.ListId_OverrideForStore, storeId);
            model.SegmentId = defaultSegmentId;
            newsmanSettings.SegmentId = defaultSegmentId;
            await _settingService.SaveSettingOverridablePerStoreAsync(newsmanSettings, settings => settings.SegmentId, model.SegmentId_OverrideForStore, storeId);

            ViewData["syncUrlCron"] = "https://" + HttpContext.Request.Host.Value + "/Plugins/Newsman/Sync?apikey=" + model.ApiKey + "&listId=" + model.ListId + "&segmentId=" + model.SegmentId + "&limit=9000&cronLast=true";
            ViewData["syncUrl"] = "https://" + HttpContext.Request.Host.Value + "/Plugins/Newsman/Sync?apikey=" + model.ApiKey + "&listId=" + model.ListId + "&segmentId=" + model.SegmentId;

            return View("~/Plugins/Misc.Newsman/Views/Configure.cshtml", model);
        }

        [HttpPost, ActionName("Configure")]
        [FormValueRequired("save")]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!ModelState.IsValid)
                return await Configure();

            //load settings for a chosen store scope
            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var newsmanSettings = await _settingService.LoadSettingAsync<NewsmanSettings>(storeId);

            //save settings
            newsmanSettings.UserId = model.UserId.Trim();
            newsmanSettings.ApiKey = model.ApiKey.Trim();
            newsmanSettings.ImportType = model.ImportType;
            newsmanSettings.AllowApi = model.AllowApi;
            newsmanSettings.ListId = model.ListId;
            newsmanSettings.SegmentId = model.SegmentId;

            await _settingService.SaveSettingAsync(newsmanSettings, x => x.UserId, clearCache: false);
            await _settingService.SaveSettingAsync(newsmanSettings, x => x.ApiKey, clearCache: false);
            await _settingService.SaveSettingAsync(newsmanSettings, x => x.ImportType, clearCache: false);
            await _settingService.SaveSettingAsync(newsmanSettings, x => x.AllowApi, clearCache: false);
            await _settingService.SaveSettingOverridablePerStoreAsync(newsmanSettings, x => x.ListId, model.ListId_OverrideForStore, storeId, false);

Nop.Plugin.Misc.Newsman/Views/Configure.cshtml
@model Nop.Plugin.Misc.Newsman.Models.ConfigurationModel
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="Newsman" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <p>
                    NEWSMAN
                    <br />
                    For plugin configuration follow these steps:<br />
                    <br />
                    1. Sign up for a <a href="https://newsman.com" target="_blank"> Newsman account</a>.<br />
                    2. Log in at the Newsman service.<br />
                    3. Create a list.<br />
                    4. Get your API Key.
                </p>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="UserId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UserId" asp-required="true" html-attributes="@(new { value = Model.UserId })" />
                        <span asp-validation-for="UserId"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="ApiKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ApiKey" asp-required="true" html-attributes="@(new { value = Model.ApiKey })" />
                        <span asp-validation-for="ApiKey"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="ImportType" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="ImportType" asp-items="Model.AvailableImportTypes" asp-required="true" />
                        <span asp-validation-for="ImportType"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="AllowApi" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="AllowApi" asp-items="Model.AvailableApi" />
                        <span asp-validation-for="AllowApi"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ListId_OverrideForStore" asp-input="ListId" asp-store-scope="Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ListId" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="ListId" asp-items="Model.AvailableLists" />
                        <span asp-validation-for="ListId"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SegmentId_OverrideForStore" asp-input="SegmentId" asp-store-scope="Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SegmentId" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="SegmentId" asp-items="Model.AvailableSegments" />
                        <span asp-validation-for="SegmentId"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <p>
                        <br />
                        Synchronization URL, can be used for CRON JOB to auto sync, last x subscibers/customers: <a href="@ViewData["syncUrlCron"].ToString()" target="_blank">@ViewData["syncUrlCron"].ToString()</a>
                        <br />
                        <br />
                        Synchronization URL, all database, it should be done one time: <a href="@ViewData["syncUrl"].ToString()" target="_blank">@ViewData["syncUrl"].ToString()</a>
                    </p>
                </div>

                <div class="form-group row">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>